# Generated by Django 3.0.2 on 2020-01-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careneeder',
            fields=[
                ('cacreneeder_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.IntegerField(default='')),
                ('dob', models.DateField(default='0')),
                ('payee', models.IntegerField(default='0')),
                ('requirment', models.CharField(default='', max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(default='', max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.IntegerField(default='0')),
                ('dob', models.DateField(default='')),
                ('milestone', models.IntegerField(default='0')),
                ('review', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
