# Generated by Django 3.0.2 on 2020-01-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careneeder',
            old_name='requirment',
            new_name='require',
        ),
    ]
