# Generated by Django 3.0.2 on 2020-01-05 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_auto_20200105_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
